import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Brain, Trophy, Zap, Star, ArrowRight, Users, Target, Shield, Sparkles, ChevronRight } from 'lucide-react';
import { motion } from 'framer-motion';
import { useCountUp } from '@/hooks/useCountUp';
import { useLanguage } from '@/contexts/LanguageContext';

const fadeUp = {
  initial: { opacity: 0, y: 30 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
};

function AnimatedStat({ value, suffix, label }: { value: number; suffix: string; label: string }) {
  const { count, ref } = useCountUp(value, 2000);
  return (
    <div ref={ref} className="text-center">
      <div className="font-display text-4xl font-bold text-gradient">
        {count}{suffix}
      </div>
      <div className="mt-1 text-sm text-muted-foreground">{label}</div>
    </div>
  );
}

export default function Landing() {
  const { t } = useLanguage();

  const features = [
    { icon: Brain, title: t('aiPowered'), desc: 'Dynamic questions generated by AI that adapt to your skill level' },
    { icon: Zap, title: t('instantFeedback'), desc: 'Get explanations for every answer and learn as you play' },
    { icon: Trophy, title: t('competeClimb'), desc: 'Real-time leaderboard with badges, streaks, and levels' },
    { icon: Star, title: t('multipleCategories'), desc: 'Science, History, Tech, and more — always something new' },
  ];

  const stats = [
    { value: 10, suffix: 'K+', label: t('questionsGenerated') },
    { value: 5, suffix: 'K+', label: t('activePlayers') },
    { value: 50, suffix: '+', label: t('quizCategories') },
    { value: 99, suffix: '%', label: t('uptime') },
  ];

  const steps = [
    { step: '01', title: t('createAccount'), desc: 'Sign up in seconds and pick your favorite categories.', icon: Users },
    { step: '02', title: t('startQuiz'), desc: 'AI generates unique questions tailored to your level.', icon: Target },
    { step: '03', title: t('learnCompete'), desc: 'Get instant feedback, earn XP, and climb the leaderboard.', icon: Trophy },
  ];

  return (
    <div className="min-h-[calc(100vh-4rem)]">
      {/* Hero */}
      <section className="relative overflow-hidden py-24 md:py-32 lg:py-40">
        <div className="absolute inset-0 gradient-hero opacity-5" />
        <div className="absolute top-20 left-10 h-72 w-72 rounded-full bg-primary/20 blur-[100px] -z-10" />
        
        <div className="container mx-auto px-4 relative z-10">
          <div className="grid lg:grid-cols-2 gap-12 lg:gap-8 items-center">
            
            {/* Left Column: Text Content */}
            <motion.div 
              initial={{ opacity: 0, x: -50 }} 
              animate={{ opacity: 1, x: 0 }} 
              transition={{ duration: 0.6, ease: "easeOut" }}
              className="text-left text-center lg:text-left flex flex-col items-center lg:items-start"
            >
              <motion.div
                className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl gradient-primary animate-pulse-glow shadow-lg shadow-primary/30"
                animate={{ rotate: [0, 5, -5, 0] }}
                transition={{ repeat: Infinity, duration: 4, ease: 'easeInOut' }}
              >
                <Brain className="h-8 w-8 text-white" />
              </motion.div>
              
              <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary mb-6 backdrop-blur-sm">
                <Sparkles className="h-4 w-4" />
                Next-Gen AI Learning
              </div>
              
              <h1 className="font-display text-5xl font-extrabold tracking-tight md:text-7xl lg:text-7xl xl:text-8xl leading-none mb-6">
                Learn Smarter with <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary">QuizAI</span>
              </h1>
              
              <p className="mt-4 max-w-xl text-lg text-muted-foreground md:text-xl font-medium mb-10">
                AI-powered quizzes that adapt to your knowledge level. Compete with friends, earn badges, and climb the leaderboard in real-time.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
                <Link to="/auth" className="w-full sm:w-auto">
                  <Button size="lg" className="w-full sm:w-auto bg-gradient-to-r from-primary to-secondary text-white hover:opacity-90 transition-opacity gap-2 text-lg h-14 px-8 shadow-xl shadow-primary/25 rounded-full">
                    {t('startPlaying')} <ArrowRight className="h-5 w-5" />
                  </Button>
                </Link>
                <Link to="/leaderboard" className="w-full sm:w-auto">
                  <Button size="lg" variant="outline" className="w-full sm:w-auto gap-2 text-lg h-14 px-8 rounded-full border-border/60 hover:bg-muted/50 backdrop-blur-sm">
                    <Trophy className="h-5 w-5 text-yellow-500" /> {t('viewLeaderboard')}
                  </Button>
                </Link>
              </div>
            </motion.div>

            {/* Right Column: 3D Robot Image */}
            <motion.div 
              initial={{ opacity: 0, x: 50, scale: 0.9 }} 
              animate={{ opacity: 1, x: 0, scale: 1 }} 
              transition={{ duration: 0.6, delay: 0.2, ease: "easeOut" }}
              className="relative hidden md:block"
            >
              {/* Glowing orb behind robot */}
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[80%] h-[80%] bg-gradient-to-tr from-primary/40 to-secondary/40 blur-[100px] -z-10 rounded-full mix-blend-multiply dark:mix-blend-screen" />
              
              <img 
                src="/robot-thinking.png" 
                alt="AI Robot Thinking" 
                className="w-full max-w-[600px] mx-auto h-auto drop-shadow-2xl animate-float"
              />
              
              {/* Floating aesthetic UI cards */}
              <motion.div 
                animate={{ y: [0, -10, 0] }}
                transition={{ repeat: Infinity, duration: 5, ease: 'easeInOut' }}
                className="absolute top-10 -left-10 bg-card/80 backdrop-blur-md border border-border/50 p-4 rounded-2xl shadow-xl flex items-center gap-3"
              >
                <div className="bg-green-500/20 p-2 rounded-lg"><Target className="h-6 w-6 text-green-500"/></div>
                <div>
                  <div className="text-sm font-bold">Accuracy</div>
                  <div className="text-xs text-muted-foreground">+99% Improved</div>
                </div>
              </motion.div>

              <motion.div 
                animate={{ y: [0, 15, 0] }}
                transition={{ repeat: Infinity, duration: 6, ease: 'easeInOut', delay: 1 }}
                className="absolute bottom-20 -right-5 bg-card/80 backdrop-blur-md border border-border/50 p-4 rounded-2xl shadow-xl flex items-center gap-3"
              >
                <div className="bg-primary/20 p-2 rounded-lg"><Brain className="h-6 w-6 text-primary"/></div>
                <div>
                  <div className="text-sm font-bold">Smart AI</div>
                  <div className="text-xs text-muted-foreground">Adapts instantly</div>
                </div>
              </motion.div>
            </motion.div>
            
          </div>
        </div>
      </section>

      {/* Stats with animated counters */}
      <section className="py-16 border-y border-border bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-2 gap-8 md:grid-cols-4">
            {stats.map((s, i) => (
              <motion.div key={s.label} {...fadeUp} transition={{ delay: i * 0.1 }}>
                <AnimatedStat value={s.value} suffix={s.suffix} label={s.label} />
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24">
        <div className="container mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-16">
            <h2 className="font-display text-3xl font-bold md:text-4xl mb-4">
              {t('whyQuizAI')} <span className="text-gradient">QuizAI</span>?
            </h2>
          </motion.div>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                {...fadeUp}
                transition={{ delay: i * 0.1, duration: 0.5 }}
                className="group rounded-2xl border border-border bg-card p-6 card-shadow hover:card-shadow-hover transition-all duration-300 hover:-translate-y-1"
              >
                <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl gradient-primary">
                  <f.icon className="h-6 w-6 text-primary-foreground" />
                </div>
                <h3 className="font-display text-lg font-semibold mb-2">{f.title}</h3>
                <p className="text-sm text-muted-foreground">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-24 bg-muted/30">
        <div className="container mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-16">
            <h2 className="font-display text-3xl font-bold md:text-4xl mb-4">
              {t('howItWorks')} <span className="text-gradient">{t('works')}</span>
            </h2>
          </motion.div>
          <div className="grid gap-8 md:grid-cols-3 max-w-4xl mx-auto">
            {steps.map((s, i) => (
              <motion.div key={s.step} {...fadeUp} transition={{ delay: i * 0.15 }} className="relative text-center">
                <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl gradient-primary">
                  <s.icon className="h-8 w-8 text-primary-foreground" />
                </div>
                <span className="font-display text-sm font-bold text-primary">{s.step}</span>
                <h3 className="font-display text-xl font-semibold mt-1 mb-2">{s.title}</h3>
                <p className="text-sm text-muted-foreground">{s.desc}</p>
                {i < steps.length - 1 && (
                  <ChevronRight className="hidden md:block absolute top-8 -right-5 h-6 w-6 text-muted-foreground/40" />
                )}
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonial */}
      <section className="py-24">
        <div className="container mx-auto px-4">
          <motion.div {...fadeUp} className="max-w-3xl mx-auto text-center">
            <div className="flex justify-center gap-1 mb-6">
              {[...Array(5)].map((_, i) => (
                <Star key={i} className="h-6 w-6 fill-primary text-primary" />
              ))}
            </div>
            <blockquote className="font-display text-2xl md:text-3xl font-semibold leading-relaxed mb-6">
              "QuizAI transformed how I study. The adaptive difficulty keeps me challenged, and the leaderboard keeps me motivated!"
            </blockquote>
            <div className="text-muted-foreground">
              <span className="font-semibold text-foreground">Sarah K.</span> · Computer Science Student
            </div>
          </motion.div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 bg-muted/30">
        <div className="container mx-auto px-4">
          <motion.div {...fadeUp} className="max-w-2xl mx-auto text-center">
            <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl gradient-primary">
              <Shield className="h-8 w-8 text-primary-foreground" />
            </div>
            <h2 className="font-display text-3xl font-bold md:text-4xl mb-4">
              {t('readyTo')} <span className="text-gradient">{t('levelUp')}</span>?
            </h2>
            <p className="text-muted-foreground mb-8 text-lg">
              Join thousands of learners who are making education fun. Start your quiz journey today — it's completely free!
            </p>
            <Link to="/auth">
              <Button size="lg" className="gradient-primary text-primary-foreground gap-2 text-lg px-10 glow-primary">
                {t('getStartedFree')} <ArrowRight className="h-5 w-5" />
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-8">
        <div className="container mx-auto px-4">
          <div className="flex flex-col items-center gap-4 md:flex-row md:justify-between">
            <div className="flex items-center gap-2">
              <Brain className="h-5 w-5 text-primary" />
              <span className="font-display font-semibold">QuizAI</span>
            </div>
            <div className="flex gap-6 text-sm text-muted-foreground">
              <Link to="/quiz" className="hover:text-primary transition-colors">{t('play')}</Link>
              <Link to="/leaderboard" className="hover:text-primary transition-colors">{t('leaderboard')}</Link>
              <Link to="/auth" className="hover:text-primary transition-colors">{t('signIn')}</Link>
            </div>
            <p className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} QuizAI. {t('allRightsReserved')} <span className="font-semibold text-foreground">smart_editor301</span>
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
